### ISSUE TITLE
Auth is ready for review!

### ISSUE THREAD

**Issue by lakhtea** [lakhtea/bootube#6]
Login/Logout/Sign up/Demo User functionality is working + css and basic navbar/sidebar css is done! Please check it out when you have the time!

**Comment by lakhtea** [comment]
https://bootube.herokuapp.com/#/

**Comment by danemauland** [comment]
Great work on your styling! See below for edits to be made:

# Splash
If the menu button is going to have functionality, ignore this. If it's just there because it's on youtube, remove it
Search box border is off--wrong color and the border ends up inside the search box
Add cursor mouse over effect to the search icon

# Auth
Dispatch a "REMOVE_SESSION_ERRORS" action when sign in/sign up component will dismount so errors don't carry over between the two forms
Add hover effects to Next/Demo User buttons
## Sign In
The "Use 6 or more characters" text stands out too much--maybe make it smaller and a little darker so it blends into the background some mare
## Sign Up
I'm able to sign up with a blank email
I'm able to create an account with the same email as another account

**Comment by lakhtea** [comment]
Splash: Menu will hopefully have functionality, I will remove it if I can't make it to that point. Search box border & search icon cursor issues fixed!
Auth: Cleared errors when successfully entering in a correct username. Added hover effects to next/demo user buttons.
Sign in: Done!
Sign Up: Fixed this issue as well! I only put email into my user tables later-on and forgot to add validations for it!

**Comment by danemauland** [comment]
Almost there! Just a few more things:

Auth
Also clear errors when the component will unmount. If I try to login with a bad email/username, and then click "sign up instead", the error still shows on the sign up form.

Sign In
No error displayed when trying to click next with no email/username entered

Sign Up
Hover effect missing on "next" button
Add padding to the top or bottom of error messages so they are spaced out a little if there are multiple

**Comment by lakhtea** [comment]
All done with these reccs!

**Comment by danemauland** [comment]
Great work!
